### PR TITLE
update binaries to newer versions

### PR DESCRIPTION
**Pull request by kc1awv**
Update binaries to latest available versions for most programs. Updating at least the MMDVMHost should solve the issue of supporting MMDVM(_HS) v1.6.0+ firmware, and maintains backwards compatibility with v1.5.2 currently available in Pi-Star repositories.

I do request that other folks test this before merging to main, please.

### CODE REVIEW

**Comment by MW0MWZ** [comment]
Steve, Sorry I don't accept binary merges, I can add the new bins, but there will be many things that break if I do that. Changes to the way MMDVMHost talks to MMDVM boards will take repeaters offline.

**Comment by kc1awv** [comment]
Experience here has been that the latest MMDVMHost is backwards compatible with the MMDVM protocol V1 used by firmware prior to v1.6.0+

I can check with @g4klx to be 100% certain too.

**Comment by ve2opn** [comment]
@kc1awv where is this "MMDVM(_HS) v1.6.0+ firmware" ?

**Comment by kc1awv** [comment]
> @kc1awv where is this "MMDVM(_HS) v1.6.0+ firmware" ?

A bit out of scope here, but readily available at the appropriate repositories.

Closing PR.

**Comment by ve2opn** [comment]
@kc1awv 
These huge (why are so huge?) binaries simply don't work at all on my setups. Sorry ... 
No time an willing to give you more useful feedback. Regards.

**Pull request closed without merging**
